Writing ic_play_tile_3d.png to android/app/src/main/res/drawable/ic_play_tile_3d.png...
Writing ic_treasure_chest_3d.png to android/app/src/main/res/drawable/ic_treasure_chest_3d.png...
Writing ic_card_pedestal_3d.png to android/app/src/main/res/drawable/ic_card_pedestal_3d.png...
Writing bg_galaxy_spiral.png to android/app/src/main/res/drawable/bg_galaxy_spiral.png...
Writing avatar_sangam.png to android/app/src/main/res/drawable/avatar_sangam.png...
Writing avatar_trexy.png to android/app/src/main/res/drawable/avatar_trexy.png...

Success! All 6 image files have been created in android/app/src/main/res/drawable/